# 项目配置
like:
  upload-directory: D://javaa/volcano/uploads/imag/ # 上传目录
  # 验证码配置
  captcha:
    # 是否开启验证码
    status: true
    # 验证码有效时长
    expire: 120
    # 验证码缓存键名
    token: "captcha:key:"

# 服务配置
server:
  port: 8082
  servlet:
    context-path: /

# 框架配置
spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /api/static/**
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher
  # 数据源配置
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource # 数据源类型
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver # MySql的驱动
      url: jdbc:mysql://127.0.0.1:3306/volcano?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
      username: root # 数据库账号
      password: root # 数据库密碼
      #配置监控统计拦截的filters,去掉后监控界面SQL无法进行统计，wall用于防火墙
      filters: stat,wall,log4j,config
      max-active: 100 #最大连接数
      initial-size: 1 #初始化大小
      min-idle: 1 #最小连接数
      max-wait: 6000 # 配置获取连接等待超时的时间
      #  配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #  配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 600000
      #  配置一个连接在池中最大生存的时间，单位是毫秒
      max-evictable-idle-time-millis: 1000000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      mxa-pool-prepared-statement-per-connection-size: 20
      keep-alive: true
      phy-max-use-count: 100
      db-type: mysql
  # 限制配置
  servlet:
    multipart:
      max-file-size: 100MB    # 文件上传大小限制
      max-request-size: 100MB # 文件最大请求限制
      enabled: true
  # Redis配置
  redis:
    host: 192.168.64.150   # Redis服务地址
    port: 6379        # Redis端口
    password: 123456  # Redis密码
    database: 0       # 数据库索引
    timeout: 5000     # 连接超时
    lettuce:
      pool:
        max-wait: 30000 # 连接池最大阻塞等待时间(使用负数表示没有限制,默认-1)
        max-active: 100 # 连接池最大连接数(使用负数表示没有限制,默认8)
        max-idle: 20    # 连接池中的最大空闲连接(默认8)
        min-idle: 0     # 连接池中的最小空闲连接(默认0)

# Mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  typeAliasesPackage: com.mdd.**.mapper
  global-config:
    banner: false
    db-config:
      table-prefix: va_
  configuration-properties:
    prefix: va_

# Sa-token配置
sa-token:
  token-name: like-admin  # token的名称
  timeout: 2592000        # token有效期单位s(默认30天,-1代表永不过期)
  activity-timeout: -1    # token临时有效期(指定时间无操作掉线)
  is-concurrent: true     # 是否允许同一账号并发登录
  is-share: false         # 多人同登账号共用token
  token-style: random-64  # token生成的风格
  is-print: false         # 打印版本字符画
  is-log: false           # 是否输出操作日志