# 项目配置
like:
  upload-directory: D://javaa/volcano/uploads/imag/ # 上传目录

# 框架配置
spring:
  # 数据源配置
  # 数据源配置
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource # 数据源类型
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver # MySql的驱动
      url: jdbc:mysql://127.0.0.1:3306/volcano?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
      username: root # 数据库账号
      password: root # 数据库密碼

  # Redis配置
  redis:
    host: 192.168.64.170   # Redis服务地址
    port: 6379        # Redis端口
    password: 123456  # Redis密码
    database: 0       # 数据库索引

# Mybatis-plus配置 【是否开启SQL日志输出】
#mybatis-plus:
#    configuration:
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl